---
name: Device-SerialPins
version: v0.0.1
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
abstract: per-pin low-level serial port access
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Device-SerialPins
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://scratchcomputing.com/svn/Device-SerialPins/trunk
build_requires:
  Module::Build: 0.26
  Test::More: 0
provides:
  Device::SerialPins:
    file: lib/Device/SerialPins.pm
    version: v0.0.1
  Device::SerialPins::Bits:
    file: lib/Device/SerialPins.pm
generated_by: Module::Build version 0.2809
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
